language: cpp
os: linux
dist: bionic
compiler:
  - g++-8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8

install:
  - bash install-framerat.sh --no-build

script:
  - bash install-framerat.sh --ci

notifications:
  email:
    recipients:
      - d3psigames@gmail.com
    on_success: always
    on_failure: always
