name: macOS C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-11.0, macos-10.15, macos-latest ]
    name: Compilation on ${{ matrix.os }}
    steps:
     - name: Checkout code
       uses: actions/checkout@master
     - name: Cache VulkanSDK
       uses: actions/cache@v1
       env:
         cache-name: cache-vk-sdk-macos
       with:
         path: vulkan-sdk.dmg
         key: ${{ env.cache-name }}
     - name: Install dependencies
       run: |
         bash install-framerat.sh --no-build
         [[ ! -f "vulkan-sdk.dmg" ]] && curl -L --silent --show-error --output vulkan-sdk.dmg https://sdk.lunarg.com/sdk/download/latest/mac/vulkan-sdk.dmg?u=
         hdiutil attach vulkan-sdk.dmg
         cd /Volumes && cd vulkansdk-macos-* && ./install_vulkan.py --force-install && cd ..
     - name: Build
       run: bash install-framerat.sh --ci
