name: Windows C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, windows-latest ]
    name: Compilation on ${{ matrix.os }}
    steps:
     - name: Checkout code
       uses: actions/checkout@master
     - name: Cache VulkanSDK
       uses: actions/cache@v1
       env:
         cache-name: cache-vk-sdk-win
       with:
         path: VulkanSDK.exe
         key: ${{ env.cache-name }}
     - name: Add msbuild to PATH
       uses: microsoft/setup-msbuild@v1.0.2
     - name: Download VulkanSDK
       run: if not exist VulkanSDK.exe curl -L --silent --show-error --output VulkanSDK.exe https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe?u=
       shell: cmd
     - name: Install VulkanSDK
       run: VulkanSDK.exe /S
       shell: cmd
     - name: Initialize submodules
       run: git submodule update --init --recursive
       shell: cmd
     - name: Generate Makefiles
       run: cmake -G "Visual Studio 16 2019" .
       shell: cmd
     - name: Build
       run: msbuild FRAMERAT_EXAMPLES.sln
       shell: cmd
